# packages/tasks/main.yml

- name: Disable unwanted system services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  failed_when: false
  loop: "{{ services_disable }}"

- name: Start and enable services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ services_enable }}"
