# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"

Vagrant.configure("2") do |config|
  config.vm.box = "file://build/fedora-33-amd64-qemu.box"
  config.vm.hostname = "vagrant-fedora-33"

  config.vm.provider "libvirt" do |v|
    v.cpus = 2
    v.disk_bus = "scsi"
    v.driver = "kvm"
    v.host = "localhost"
    v.memory = 2048
  end
end
