# SPDX-License-Identifier: ISC
---
- name: Add packages
  ansible.builtin.package:
    name: consul
    state: present
  diff_mode: false

- name: Open required ports
  ansible.posix.firewalld:
    port: "{{ item.port }}"
    state: enabled
    permanent: true
  loop:
    - port: 8300/tcp
    - port: 8301/tcp
    - port: 8301/udp
    - port: 8302/tcp
    - port: 8302/udp
    - port: 8500/tcp
    - port: 8600/tcp
    - port: 8600/udp
    - port: 21000-21255/tcp
    - port: 21000-21255/udp
  loop_control:
    label: "{{ item.port }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: consul
    group: consul
    mode: 0750
  loop:
    - path: /etc/consul
    - path: /etc/consul.d
    - path: /etc/consul/data
    - path: /etc/consul/plugins
  loop_control:
    label: "{{ item.path }}"

- name: Configure consul
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: consul
    group: consul
    mode: 0640
  loop:
    - src: consul.env.j2
      dest: /etc/consul/consul.env
    - src: consul.hcl.j2
      dest: /etc/consul/consul.hcl
  loop_control:
    label: "{{ item.dest }}"

- name: Configure consul.service
  ansible.builtin.template:
    src: consul.service.j2
    dest: /usr/lib/systemd/system/consul.service
    owner: consul
    group: consul
    mode: 0640
  register: consul_service_configured

- name: Reload systemd daemons if consul.service changed
  ansible.builtin.raw: >-
    systemctl daemon-reload
  when: consul_service_configured.changed

- name: Start and enable consul.service
  ansible.builtin.systemd:
    name: consul.service
    state: started
    enabled: true
