# SPDX-License-Identifier: ISC

- name: Add system user 'consul'
  ansible.builtin.user:
    name: consul
    state: present
    home: "/etc/consul.d"
    shell: /bin/false
    system: true

- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    recurse: true
    owner: consul
    group: consul
    mode: "0700"
  loop:
    - path: /etc/consul.d
    - path: /etc/consul/data
    - path: /etc/consul/plugins
  loop_control:
    label: "{{ item.path }}"

- name: Configure consul
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: consul
    group: consul
    mode: "0600"
  loop:
    - src: consul.env.j2
      dest: /etc/consul.d/consul.env
    - src: consul.hcl.j2
      dest: /etc/consul.d/consul.hcl
  loop_control:
    label: "{{ item.dest }}"

- name: Add hashicorp-consul-stable repository
  ansible.builtin.yum_repository:
    name: consul
    state: present
    enabled: true
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    description: hashicorp-consul-stable
    file: hashicorp-consul-stable
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    include: consul

- name: Add packages
  ansible.builtin.package:
    name: "{{ consul_packages }}"
    state: present

- name: Configure consul.service
  ansible.builtin.template:
    src: consul.service.j2
    dest: /usr/lib/systemd/system/consul.service
    owner: root
    group: root
    mode: "0644"
  register: consul_service_configured

- name: Reload systemd daemons if consul.service changed
  ansible.builtin.raw: >-
    systemctl daemon-reload
  when: consul_service_configured.changed

- name: Open required ports
  ansible.posix.firewalld:
    port: "{{ item.port }}"
    state: enabled
    permanent: true
  loop:
    - port: 8300/tcp
    - port: 8301/tcp
    - port: 8301/udp
    - port: 8302/tcp
    - port: 8302/udp
    - port: 8500/tcp
    - port: 8600/tcp
    - port: 8600/udp
    - port: 21000-21255/tcp
    - port: 21000-21255/udp
  loop_control:
    label: "{{ item.port }}"

- name: Start and enable consul.service
  ansible.builtin.systemd:
    name: consul.service
    state: started
    enabled: true
