# SPDX-License-Identifier: ISC
---
nomad_packages:
  - libvirt
  - podman
  - podman-compose
  - podman-plugins
  - nomad
  - qemu
  - unzip

nomad_bind_addr: 127.0.0.1
nomad_log_level: INFO

nomad_advertise_http: 127.0.0.1
nomad_advertise_rpc: 127.0.0.1
nomad_advertise_serf: 127.0.0.1

nomad_client_enabled: true
nomad_client_servers:
  - 127.0.0.1

nomad_consul_address: "{{ consul_bind_addr }}"

nomad_server_enabled: true
nomad_server_bootstrap_expect: "{{ play_hosts | length | int }}"

nomad_vault_enabled: true
nomad_vault_create_from_role: nomad-cluster
nomad_vault_address: "https://{{ vault_listener_address }}"
nomad_vault_ca_path: /etc/certs/ca
nomad_vault_cert_file: null # /var/certs/vault.crt
nomad_vault_key_file: null # /var/certs/vault.key
nomad_vault_tls_skip_verify: true

nomad_driver_podman_config_volumes_enabled: true
nomad_driver_podman_config_volumes_selinuxlabel: z
nomad_driver_podman_version: "0.3.0"
nomad_driver_podman_url_prefix: >-
  https://releases.hashicorp.com/nomad-driver-podman/
  {{- nomad_driver_podman_version -}}/nomad-driver-podman_
  {{- nomad_driver_podman_version -}}
