---
namespace: jcmdln
name: infranetic
description: ""
version: 0.0.0
repository: https://github.com/jcmdln/infranetic
license_file: LICENSE.md
readme: README.md
authors:
  - "Johnathan C. Maudlin <jcmdln@gmail.com>"
dependencies:
  "ansible.posix": "*"
  "ansible.utils": "*"
  "community.crypto": "*"
  "community.general": "*"
tags:
  - collection
  - consul
  - nomad
  - vault
