# SPDX-License-Identifier: ISC
---
- hosts: all
  become: true
  tasks:
    - name: Import setup role
      ansible.builtin.include_role:
        name: setup
        apply:
          tags: [setup]
      tags: [setup]

    - name: Import seaweedfs role
      ansible.builtin.include_role:
        name: seaweedfs
        apply:
          tags: [seaweedfs]
      tags: [never, seaweedfs]

    - name: Import consul role
      ansible.builtin.include_role:
        name: consul
        apply:
          tags: [consul]
      tags: [consul]

    - name: Import vault role
      ansible.builtin.include_role:
        name: vault
        apply:
          tags: [vault]
      tags: [vault]

    - name: Import nomad role
      ansible.builtin.include_role:
        name: nomad
        apply:
          tags: [nomad]
      tags: [nomad]

    - name: Import fabio role
      ansible.builtin.include_role:
        name: fabio
        apply:
          tags: [fabio]
      tags: [never, fabio]
