---
- name: Add hashicorp-nomad-stable repository
  ansible.builtin.yum_repository:
    name: nomad
    state: present
    enabled: true
    baseurl: >-
      https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    description: hashicorp-nomad-stable
    file: hashicorp
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    include: nomad

- name: Add packages
  ansible.builtin.package:
    name: "{{ nomad_packages }}"
    state: present

- name: Add user
  ansible.builtin.user:
    name: nomad
    state: present
    groups: libvirt
    append: true

- name: Start and enable user podman.socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true

#- name: Start and enable user podman.socket as user 'nomad'
#  ansible.builtin.systemd:
#    enabled: true
#    name: nomad.service
#    scope: user
#    state: started
#  become: true
#  become_method: sudo
#  become_user: nomad

- name: Create nomad_directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nomad
    group: nomad
    mode: 0755
  with_items:
    - "{{ nomad_directories }}"

- name: Download and verify nomad-driver-podman
  ansible.builtin.get_url:
    url: "{{ nomad_driver_podman_url_prefix }}_linux_amd64.zip"
    dest: /tmp/nomad-driver-podman.zip
    checksum: "sha256:{{ nomad_driver_podman_url_prefix }}_SHA256SUMS"

- name: Unarchive nomad-driver-podman
  ansible.builtin.unarchive:
    src: /tmp/nomad-driver-podman.zip
    dest: /opt/nomad/plugins
    owner: nomad
    group: nomad
    mode: 0755
    remote_src: true

- name: Configure nomad
  ansible.builtin.template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: 0755
