---
- name: Install dnf-automatic
  ansible.builtin.package:
    name: dnf-automatic
    state: present

- name: (dnf-automatic) Set apply_updates to "yes"
  ansible.builtin.lineinfile:
    line: "apply_updates = yes"
    path: /etc/dnf/automatic.conf
    regexp: "^apply_updates.*"

- name: (dnf-automatic) Set emit_via to "motd"
  ansible.builtin.lineinfile:
    line: "emit_via = motd"
    path: /etc/dnf/automatic.conf
    regexp: "^emit_via.*"

- name: (dnf-automatic) Set upgrade_type to "security"
  ansible.builtin.lineinfile:
    line: "upgrade_type = security"
    path: /etc/dnf/automatic.conf
    regexp: "^upgrade_type.*"

- name: Start and enable dnf-automatic timer
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: started
    enabled: true
