---
- name: Add hashicorp-consul-stable repository
  ansible.builtin.yum_repository:
    baseurl: >-
      https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    description: hashicorp-consul-stable
    enabled: true
    file: hashicorp
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    include: consul
    name: consul
    state: present

- name: Add packages
  ansible.builtin.package:
    name: consul
    state: present

- name: Add user
  ansible.builtin.user:
    name: consul
    state: present
