# vault/defaults/main.yml

vault_directories:
  - /etc/vault.d
  - /opt/vault
  - /opt/vault/data
  - /opt/vault/tls

vault_packages:
  - python3-cryptography
  - vault

# https://www.vaultproject.io/docs/configuration#cluster_addr
vault_cluster_address: "127.0.0.1:8201"

# https://www.vaultproject.io/docs/configuration/listener/tcp#address
vault_listener_address: "127.0.0.1:8200"

# https://www.vaultproject.io/docs/configuration/storage/consul#address
vault_storage_address: "127.0.0.1:8500"

# https://www.vaultproject.io/docs/configuration/storage/consul#path
vault_storage_path: "vault"

# https://www.vaultproject.io/docs/configuration/telemetry#statsite_address
vault_telemetry_address: "127.0.0.1:8125"

# https://www.vaultproject.io/docs/configuration/telemetry#disable_hostname
vault_telemetry_disable_hostname: true
