# SPDX-License-Identifier: ISC
---
- name: (Vault) Add system user 'vault'
  ansible.builtin.user:
    name: vault
    state: present
    home: /etc/vault.d
    shell: /bin/false
    system: true

- name: (Vault) Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: vault
    group: vault
    mode: "0700"
  loop:
    - path: /etc/vault
    - path: /etc/vault.d
    - path: /etc/vault/data
    - path: /etc/vault/plugins
    - path: /etc/vault/tls

- name: (Vault) Configure vault
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/vault.d/{{ item }}"
    owner: vault
    group: vault
    mode: "0600"
  loop:
    - vault.hcl

- name: (Vault) Add hashicorp-vault-stable repository
  ansible.builtin.yum_repository:
    name: vault
    state: present
    enabled: true
    baseurl: >-
      https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    description: hashicorp-vault-stable
    file: hashicorp-vault-stable
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    include: vault

- name: (Vault) Add packages
  ansible.builtin.package:
    name: "{{ vault_packages }}"
    state: present

- name: (Vault) Start and enable vault.service
  ansible.builtin.systemd:
    name: vault.service
    state: started
    enabled: true
