# SPDX-License-Identifier: ISC
---
- name: Prepare
  hosts: all
  tags: [always]
  tasks:
    - name: Find all playbook roles
      ansible.builtin.find:
        file_type: directory
        paths: "../../../../roles"
      delegate_to: localhost
      register: infranetic_roles

    - name: Include defaults from playbook roles
      ansible.builtin.include_vars: "{{ item.path }}/defaults/main.yml"
      loop: "{{ infranetic_roles.files }}"
      loop_control:
        label: "{{ item.path | basename }}"

- name: Converge
  hosts: all
  become: true
  roles:
    - role: setup
    - role: nomad
