# nomad/defaults/main.yml

nomad_directories:
  - /etc/nomad.d
  - /opt/nomad/data
  - /opt/nomad/plugins

nomad_packages:
  - libvirt
  - podman
  - podman-compose
  - podman-plugins
  - nomad
  - qemu

nomad_driver_podman_version: "0.2.0"
nomad_driver_podman_url_prefix: >-
  https://releases.hashicorp.com/nomad-driver-podman/
  {{- nomad_driver_podman_version -}}/nomad-driver-podman_
  {{- nomad_driver_podman_version -}}
