# site.yml

- become: true
  hosts: default

  pre_tasks:
    - name: Add HashiCorp repository
      ansible.builtin.yum_repository:
        baseurl: "https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable"
        description: "hashicorp"
        enabled: true
        exclude: "vagrant*"
        file: hashicorp
        gpgcheck: true
        gpgkey: "https://rpm.releases.hashicorp.com/gpg"
        name: "hashicorp"

  roles:
    - role: consul
    - role: nomad
    - role: vault
    - role: vagrant
      when:
        - vagrant_target is defined
        - vagrant_target
