---
all:
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_pass: infranetic
    ansible_user: infranetic

servers:
  hosts:
    local-server-1:
    local-server-2:
    local-server-3:
