# SPDX-License-Identifier: ISC

{% if item.registry is defined and '/' not in item.image %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN \
if [ -n "$(command -v dnf)" ]; then \
    dnf -y install ca-certificates python3 sudo systemd && \
    dnf -y autoremove && \
    dnf clean all; \
elif [ -n "$(command -v apt)" ]; then \
    apt update && \
    apt -y install ca-certificates python3 sudo systemd && \
    apt autoremove && \
    apt auto clean; \
fi

CMD ["/bin/bash"]
