# SPDX-License-Identifier: ISC
---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: podman

platforms:
  - name: instance
    image: registry.fedoraproject.org/fedora:35
    command: /sbin/init
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  config_options:
    defaults:
      any_errors_fatal: true
      bin_ansible_callbacks: true
      callback_whitelist: profile_roles,timer
      command_warnings: false
      deprecation_warnings: false
      gathering: smart
      stdout_callback: community.general.yml
    diff:
      always: true

verifier:
  name: ansible
