# vagrant/tasks/main.yml

- name: Add Vagrant pubkey
  ansible.posix.authorized_key:
    user: infranetic
    state: present
    key: https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub

- name: Grant password-less sudo to user "infranetic"
  blockinfile:
    block: |
      # Allow Vagrant to perform ssh setup
      infranetic ALL=(ALL) NOPASSWD: ALL
    path: /etc/sudoers
