# SPDX-License-Identifier: ISC
---
consul_packages:
  - consul

consul_advertise_addr: 127.0.0.1
consul_bind_addr: 127.0.0.1
consul_bootstrap_expect: "{{ play_hosts | length | int }}"
consul_client_addr: 127.0.0.1
consul_server: true
consul_ui_config_enabled: true
