# SPDX-License-Identifier: ISC
---
- name: Ensure libvirt group exists
  ansible.builtin.user:
    name: libvirt
    state: present

- name: Add nomad user
  ansible.builtin.user:
    name: nomad
    state: present
    groups: libvirt
    append: true
    home: /etc/nomad.d
    shell: /bin/false
    system: true

# FIXME: If your operating system's default ephemeral port range overlaps with
# Nomad's dynamic port range, you should tune the OS to avoid this overlap.
# - https://www.nomadproject.io/docs/install/production/requirements#ports-used
- name: Open required ports
  ansible.posix.firewalld:
    port: "{{ item.port }}"
    state: enabled
    permanent: true
  loop:
    - port: 4646/tcp
    - port: 4647/tcp
    - port: 4648/tcp
    - port: 4648/udp
  loop_control:
    label: "{{ item.port }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: nomad
    group: nomad
    mode: 0750
  loop:
    - path: /etc/nomad
    - path: /etc/nomad.d
    - path: /etc/nomad/data
    - path: /etc/nomad/plugins
  loop_control:
    label: "{{ item.path }}"

- name: Configure nomad
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: nomad
    group: nomad
    mode: 0640
  loop:
    - src: nomad.hcl.j2
      dest: /etc/nomad.d/nomad.hcl
  loop_control:
    label: "{{ item.dest }}"

- name: Add packages
  ansible.builtin.package:
    name: "{{ common | union(targets[ansible_os_family | lower]) }}"
    state: present
    update_cache: "{{ true if ansible_os_family | lower == 'debian' else omit }}"
  vars:
    common:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - nomad
      - nomad-autoscaler
      - qemu-kvm
      - unzip
    targets:
      debian:
        - libvirt-clients
        - libvirt-daemon-system
      redhat:
        - libvirt-client
        - libvirt-daemon

- name: Start and enable docker.service
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true

- name: Start nomad.service
  ansible.builtin.systemd:
    name: nomad.service
    state: started
    enabled: true
