# SPDX-License-Identifier: ISC
---
- name: Add system user 'vault'
  ansible.builtin.user:
    name: vault
    state: present
    home: /etc/vault.d
    shell: /bin/false
    system: true

- name: Open required ports
  ansible.posix.firewalld:
    port: "{{ item.port }}"
    state: enabled
    permanent: true
  loop:
    - port: 8125/tcp
    - port: 8200/tcp
    - port: 8201/tcp
    - port: 8500/tcp
  loop_control:
    label: "{{ item.port }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: vault
    group: vault
    mode: 0750
  loop:
    - path: /etc/vault
    - path: /etc/vault.d
    - path: /etc/vault/data
    - path: /etc/vault/plugins
    - path: /etc/vault/tls
  loop_control:
    label: "{{ item.path }}"

- name: Configure vault
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: vault
    group: vault
    mode: 0640
  loop:
    - src: vault.hcl.j2
      dest: /etc/vault.d/vault.hcl
  loop_control:
    label: "{{ item.dest }}"

- name: Add packages
  ansible.builtin.package:
    name: "{{ vault_packages }}"
    state: present

- name: Start and enable vault.service
  ansible.builtin.systemd:
    name: vault.service
    state: started
    enabled: true
