# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"

Vagrant.configure("2") do |config|

  config.vm.define :vm1 do |vm1|
    vm1.vm.box = "file://build/compute-amd64-qemu.box"
    vm1.vm.hostname = "compute-1"

    vm1.vm.provider "libvirt" do |v|
      #v.cpu_mode = "host-passthrough"
      v.cpus = 2
      v.disk_bus = "scsi"
      v.driver = "kvm"
      v.host = "localhost"
      v.memory = 2048
      v.qemu_use_session = true
      v.system_uri = "qemu:///system"
      v.uri = "qemu:///session"
    end
  end

end
