# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"

Vagrant.configure("2") do |config|
  config.ssh.verify_host_key = false

  config.vm.define :compute_1 do |c|
    c.ssh.password = "infranetic"
    c.ssh.username = "infranetic"
    c.vm.box = "file://build/compute-amd64-qemu.box"
    c.vm.hostname = "compute-1"
    c.vm.provider "libvirt" do |v|
      v.cpus = 2
      v.loader = "/usr/share/edk2/ovmf/OVMF_CODE.fd"
      v.memory = 2048
    end
  end

end
