# SPDX-License-Identifier: ISC
---
- name: Update system packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install system packages
  ansible.builtin.package:
    name: "{{ setup_packages }}"
    state: present
