# SPDX-License-Identifier: ISC
---
name: build

on:
  pull_request:
    paths:
      - ".github/**"
      - "fedora-kickstart.cfg"
      - "fedora.pkr.hcl"
      - "roles/setup/**"
  push:
    paths:
      - ".github/**"
      - "fedora-kickstart.cfg"
      - "fedora.pkr.hcl"
      - "roles/setup/**"
  workflow_dispatch:

jobs:
  fedora:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_arch:
          - aarch64
          - x86_64
        os_version:
          - 34
          - 35
    steps:
      - uses: actions/checkout@v2

      - name: apt
        run: |
          sudo apt update
          sudo apt install -y ansible ovmf qemu-kvm

      - name: packer init
        run: packer init fedora.pkr.hcl

      - name: packer validate
        run: packer validate -syntax-only fedora.pkr.hcl

      - name: packer build
        run: >-
          packer build
          -color=false
          -except="manifest,shell,shell-local,vagrant"
          -on-error=abort
          -var="os_version=${{ matrix.os_version }}"
          -var="qemu_accel=tcg"
          -var="qemu_arch=${{ matrix.os_arch }}"
          -var="qemu_bios=/usr/share/ovmf/OVMF.fd"
          -var="qemu_cpu=max"
          -var="qemu_ssh_timeout=2h"
          fedora.pkr.hcl
