# SPDX-License-Identifier: ISC

name: build

on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - fedora-kickstart.cfg
      - fedora.pkr.hcl
      - roles/setup/**
      - site.yml
  push:
    paths:
      - .github/workflows/build.yml
      - fedora-kickstart.cfg
      - fedora.pkr.hcl
      - roles/setup/**
      - site.yml
  workflow_dispatch:

jobs:
  fedora:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_version:
          - 34
          - 35
    steps:
      - uses: actions/checkout@v3

      - name: apt
        run: sudo apt update && sudo apt install -y ansible ovmf qemu-kvm

      - name: packer init
        run: packer init ./tools/fedora.pkr.hcl

      - name: packer validate
        run: packer validate -syntax-only ./tools/fedora.pkr.hcl

      - name: packer build
        run: >-
          packer build -color=false -except="manifest,shell,shell-local,vagrant" -on-error=abort
          -var="os_version=${{ matrix.os_version }}"
          -var="qemu_accel=tcg"
          -var="qemu_bios=/usr/share/ovmf/OVMF.fd"
          -var="qemu_cpu=qemu64"
          -var="qemu_ssh_timeout=2h"
          ./tools/fedora.pkr.hcl
