# SPDX-License-Identifier: ISC
---
name: packer

on:
  pull_request:
    paths:
      - ".github/**"
      - "fedora-kickstart.cfg"
      - "fedora.pkr.hcl"
  push:
    paths:
      - ".github/**"
      - "fedora-kickstart.cfg"
      - "fedora.pkr.hcl"
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible ovmf qemu-kvm
          ansible-galaxy collection install -fr requirements.yml

      - name: Init
        run: packer init fedora.pkr.hcl

      - name: Validate
        run: packer validate -syntax-only fedora.pkr.hcl

      - name: Build
        env:
          PACKER_LOG: 1
        run: packer build -color=false -on-error=abort fedora.pkr.hcl
