# SPDX-License-Identifier: ISC
---
name: lint

on:
  pull_request:
    paths:
      - .github/workflows/lint.yml
      - requirements/*.txt
      - roles/**
      - .ansible-lint
      - .editorconfig
      - .gitignore
      - .yamllint
      - ansible.cfg
      - site.yml
      - tox.ini
  push:
    paths:
      - .github/workflows/lint.yml
      - requirements/*.txt
      - roles/**
      - .ansible-lint
      - .editorconfig
      - .gitignore
      - .yamllint
      - ansible.cfg
      - site.yml
      - tox.ini
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ansible-lint
          - name: yamllint

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            requirements/tox.txt
            tox.ini

      - uses: actions/cache@v3
        id: cache-tox
        with:
          key: cache-tox-${{ matrix.name }}-${{ hashFiles('requirements/*.txt', 'tox.ini') }}
          path: .tox/${{ matrix.name }}

      - name: Install Tox
        run: pip install -r requirements/tox.txt

      - name: Run ${{ matrix.name }}
        run: tox -e ${{ matrix.name }}
