# SPDX-License-Identifier: ISC
---
name: lint

on:
  pull_request:
    paths:
      - ".github/**"
      - "fedora-kickstart.cfg"
      - "fedora.pkr.hcl"
  push:
    paths:
      - ".github/**"
      - "fedora-kickstart.cfg"
      - "fedora.pkr.hcl"
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          cache: "pip"
          cache-dependency-path: "requirements*.txt"
      - name: Prepare
        run: |
          pip install -r requirements.txt
          ansible-galaxy collection install -r requirements.yml

  packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: packer validate
        run: |
          packer init fedora.pkr.hcl
          packer validate -syntax-only fedora.pkr.hcl
