---
name: Test setup-ansible/roles using Ansible Molecule

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test_setup_roles:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        molecule_roles:
          - services

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: pip install -r ./ansible/setup-ansible/requirements.txt

      - run: >-
          cd ./ansible/setup-ansible/roles/${{matrix.molecule_roles}} &&
          molecule test
        env:
          ANSIBLE_PIPELINING: true
