---
name: Validate packer template

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate_packer_template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: >-
          sudo apt-get update &&
          sudo apt-get install packer

      - run: >-
          packer validate infranetic.pkr.hcl
